language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6-dev'
  - 'nightly'
install:
  - pip install -U cython pytest pytest-cov pytest-asyncio
  - pip install -Ue .
script:
  - py.test --cov=aiofile tests
  - pip uninstall -y .
