language: python
cache: pip
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -Ue '.[develop]'
script:
  - py.test --cov=aiofile tests
  - pip install -U aiomisc
  - py.test --cov=aiofile tests
  - pip uninstall -y .
